# string demo
str="  Tops Technologies"
print(str)
print(str.capitalize())
print("CaseFold :",str.casefold())
print("Center :",str.center(50))
print("Count :",str.count("ss"))
print("EndWith :",str.endswith("o"))
print(str.startswith("t"))
print(str.find("lo"))
# print(str.format(2,5))
print(str.index("ps"))
print(" ".isalnum())
print("1".isalpha())
print("a".isdecimal())
print("1".isdigit())
print("1.1".isnumeric())
print("int".isidentifier())
print("Abs".islower())
print("Abc".istitle())
print("a".isupper())
print("-".join("Tops"))
print(str.ljust(30,'*'))
#print(str.lower())
# print(str.upper())
print(str.partition(' T'))
print(str.replace("T", "t"))
print(str.split("o", maxsplit=3))
# print(str.swapcase())
# print(str.title())